### ISSUE TITLE
Applying to other dataset

### ISSUE THREAD

**Issue by syncle** [aboulch/snapnet#10]
I want to apply SnapNet to other dataset, but it is not clear whether it is applicable. For example, let's say there is indoor scan dataset, and want to generate images only inside the rooms. Does the SnapNet's camera sampling strategy handles this cases? If it requires some tweak, can you tell me how?

**Comment by aboulch** [comment]
If you want to apply SnapNet to an indoor dataset, you need to create a new sampling strategy by extending the ViewGenerator Class. It should be easy to do so, at least reduce the distance between the point and the camera in order to be in the room and not generate camera that only see the ceiling.
