### ISSUE TITLE
i have some question 

### ISSUE THREAD

**Issue by qq276399331** [aboulch/snapnet#11]
i cant do it because ,i run the demo,it will become 
Traceback (most recent call last):
  File "sem3d_test_to_sem3D_labels.py", line 7, in <module>
    from pointcloud_tools.lib.python.PcTools import Semantic3D 
ImportError: /home/lthpc/sSPG/snapnet-master/pointcloud_tools/lib/python/PcTools.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3pcl2io15savePolygonFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11PolygonMeshEb
i dont konw how to solve it

**Comment by aboulch** [comment]
Hello,
"savePolygonFile" is a function from PCL. be sure to install it and that the pcl directories are correct in the setup.py.

**Comment by qq276399331** [comment]
Hello，
Thank you much for your help，i am very happay， i can run the projiect. but
i have one question, i find the data is bigger,Can I train all data at once?

**Comment by aboulch** [comment]
Hello,
The code generate temporary files with each scene, and never load all scenes at once.
For now there is nothing in the code to split one scene that would be to big to be processed (like splitting data).
