### ISSUE TITLE
Training without RGB

### ISSUE THREAD

**Issue by maximiliangoettgens** [aboulch/snapnet#14]
Hello and thank you for the nice contribution!

I am wondering whether it is possible to train snapnet independent of color. Some experiments have shown that a RGB-trained model also performs quite well on unseen pointclouds when the color was set to 0 0 0 or 255 255 255 during training and testing - so I guess it is not strongly dependent on color. In order to improve the results even further, I am planning to remove the RGB training entirely from snapnet but was not yet successful. If I set     

>     "train_rgb" : true,

In the `config.json` , it does not train RGB, however, if I try to run the backprojection, it crashes because it tries to find the RGB model which obviously does not exist.

Any help on how to do this is appreciated - thanks again
Max

**Comment by aboulch** [comment]
Hello,
For now, the code is such that you need to train on both RGB and Composite, the flag in the config.json is only is you want to do it separately, but backproj needs both model.

You could: 
- Train a fake RGB model only for one epoch (even though there is no RGB), the fusion network should learn not to use it.
- Train two Composite models by modifying path to RGB model to look at composite images
- Modify the code in tensorflow_tester_backprojeter.py to load only the composite model

I am not I will have time right now to to push a fix on this issue.
I will try to do it by the end of July.

**Comment by maximiliangoettgens** [comment]
Hello and thanks for your input,

as far as I understand - those methods should not make a big difference from the one that I was using (except for computation times) in terms of performance (accuracy).

Did I understand correctly, that the fusion model fuses RGB and composite and hence is 'useless' if either one model is not available? I'm saying that if there is no RGB, then fusion is no more useful than composite alone and therefore you do not need it?

Thank you very much

**Comment by aboulch** [comment]
Did I understand correctly, that the fusion model fuses RGB and composite and hence is 'useless' if either one model is not available? 
==> True
I'm saying that if there is no RGB, then fusion is no more useful than composite alone and therefore you do not need it?
==> True

**Comment by maximiliangoettgens** [comment]
Okay, thanks - this made things clearer!
