### ISSUE TITLE
ImportError: No module named pointcloud_tools.lib.python.PcTools

### ISSUE THREAD

**Issue by chowkamlee81** [aboulch/snapnet#15]
I tried to run python sem3d_test_backproj_tf.py --config config.json, but landed in error showing 

ImportError: No module named pointcloud_tools.lib.python.PcTools

I have built so files using
cd pointcloud_tools
python setup.py install --home="."

Kindly let me know how to resolve this problem.

**Comment by aboulch** [comment]
Hello,
Make sure of where has been built the library.
It should be in pointcloud_tools/lib/python/
If not either move the library to match the path or modify the code 
`pointcloud_tools.lib.python.PcTools`
to match the path of your library.
