### ISSUE TITLE
Where can I download Pre-trained models

### ISSUE THREAD

**Issue by chiyandetaotie** [aboulch/snapnet#17]
Hi, @aboulch ,

Thanks for releasing this package.The link for downloading the *.npy file of the VGG weights seems to be broken (https://sites.google.com/view/boulch/publications/2017_3dor_pointclouds 
and           http://www.boulch.eu/publications/2017-3DOR-snapnet ). Is there any other place where I can get it?

**Comment by aboulch** [comment]
Hi,
I updated the link in the README.md.
It should work.
