### ISSUE TITLE
segmentation fault！

### ISSUE THREAD

**Issue by laibq** [aboulch/snapnet#18]
Hello Prof：
     Something wrong with my sem3d_train_tf.py.
     When I use python3 sem3d_train_tf.py --config config.json to train my model. It said

Error fc6 weights
Error fc6 biases
Error fc8 weights
Error fc8 biases
Error fc7 weights
Error fc7 biases

and said 'Segmentation fault (core dumped)', I have try many way to solve but didn't work. Can you tell me maybe where is the problem?

**Comment by whu-lee** [comment]
Did you solve it? I also got the same error.
