### ISSUE TITLE
download link for vgg weight

### ISSUE THREAD

**Issue by amiltonwong** [aboulch/snapnet#2]
Hi, @aboulch ,

Thanks for releasing this package. According to [this](https://github.com/aboulch/snapnet/blob/master/sem3d_train_tf.py#L30), the vgg weight file is needed. Could you list the specific download link for it? It'll be helpful as there are so many versions of vgg weight file released online.

BTW, the download [link](https://github.com/aboulch/snapnet#pre-trained-models) in readme is broken, it should be [this link](https://sites.google.com/view/boulch/publications/2017_3dor_pointclouds).
More, is it correct that the weight file "snapnet_model_fusion.zip" is just 475kB compared with other weight file with ~100MB in size?

Thanks~

**Comment by aboulch** [comment]
Hello,

Thanks for the note. I fixed the broken links and added a link to the VGG download page (the caffe model need to be processed using Kaffe to generate tensorflow weights).

The fusion network is small as it must be used with the RGB and Composite weights. You need to download the three of them.

Best,

**Comment by amiltonwong** [comment]
Hi, @aboulch ,
Thanks for your reply. I download the `VGG_ILSVRC_16_layers.caffemodel` and `VGG_ILSVRC_16_layers_deploy.prototxt` from the link mentioned in readme. However, when I use caffe-tensorflow (kaffe) package for the conversion. I came accross the following error:

```
python ../../convert.py VGG_ILSVRC_16_layers_deploy.prototxt --caffemodel=VGG_ILSVRC_16_layers.caffemodel --data-output-path=vgg16net.npy

------------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Error encountered: Unknown layer type encountered: 4
```

However, when I perform the conversion for the bvlc_model (https://github.com/BVLC/caffe/tree/master/models), I could successfully convert them. It seems Oxford Simon's VGG_ILSVRC_16_layers_deploy.prototxt has some difference against standard caffe prototxt (like [this thread](https://github.com/ethereon/caffe-tensorflow/issues/68)). Could you reply a bit further on how to convert vgg caffe model into tensorflow version?

Thanks!

**Comment by aboulch** [comment]
Hello,
I added the numpy weights to download at:
https://sites.google.com/view/boulch/publications/2017_3dor_pointclouds
Tell me if there is a problem to download them.
