### ISSUE TITLE
Not enough neighbors are considered: ffn or sfn out of range

### ISSUE THREAD

**Issue by whu-lee** [aboulch/snapnet#22]
Hello Prof：
Something wrong with  sem3d_gen_images.py.
When I use python3 sem3d_gen_images.py --config config.json. It said

Loading configuration file
bildstein_station1_xyz_intensity_rgb
  -- loading data
  -- computing mesh data
Cloud size 790299
Not enough neighbors are considered: ffn or sfn out of range! Consider increasing nnn_... Setting R=1150 to be BOUNDARY!
Not enough neighbors are considered: source of R=3073 is out of range! Consider increasing nnn_...
Number of neighborhood size increase requests for fringe neighbors: 1593
Number of neighborhood size increase requests for source: 203

Segmentation fault (core dumped)

Kindly let me know how to resolve this problem.

**Comment by aboulch** [comment]
Hello,
It seems to be related to the meshing process.
In the Sem3D.cxx file, line 484+, there are the default parameters used in my experiments.
I think you can change them and see if you can get better results.

**Comment by whu-lee** [comment]
Thank you very much for your reply, I set "gp3.setSearch Radius (3);" and "gp3.setMaximumNearestNeighbors (400);" n the Sem3D.cxx file, line 484+. The problem is solved.
Thanks for your answer !
