### ISSUE TITLE
No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '../python/Semantic3D.so'.  Stop

### ISSUE THREAD

**Issue by ChidanandKumarKS** [aboulch/snapnet#3]
I got the error below while building this library

[ 50%] Building CXX object src/CMakeFiles/Semantic3D.dir/Sem3D.cxx.o
<command-line>:0:15: warning: missing whitespace after the macro name
[ 66%] Building CXX object src/CMakeFiles/Semantic3D.dir/pointCloudLabels.cxx.o
<command-line>:0:15: warning: missing whitespace after the macro name
[ 83%] Building CXX object src/CMakeFiles/Semantic3D.dir/pointCloud.cxx.o
<command-line>:0:15: warning: missing whitespace after the macro name
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '../python/Semantic3D.so'.  Stop.
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/Semantic3D.dir/all' failed
make[1]: *** [src/CMakeFiles/Semantic3D.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Kindly provide the solution

**Comment by aboulch** [comment]
Hello,
I do not this error.
I found that on the net if you are running Ubuntu 16.04. It is somehow linked to PCL.

https://stackoverflow.com/questions/37369369/compiling-pcl-1-7-on-ubuntu-16-04-errors-in-cmake-generated-makefile

We are currently working on simplifying the framework, to be easier to use and to compile.

**Comment by ChidanandKumarKS** [comment]
As per ur suggestions in  previous link i did below:
a) sudo apt install libproj-dev
b) In CmakeLists.txt, i added list(REMOVE_ITEM PCL_LIBRARIES "vkproj4")

These two statements solved building library issues

Thanks
Kumar
