### ISSUE TITLE
How to solve the problem?

### ISSUE THREAD

**Issue by zy20091082** [aboulch/snapnet#5]
@aboulch 
**I use the default setting except the paths.
 It seems lacking the view file.**

![qq 20180305175631](https://user-images.githubusercontent.com/35857702/36968793-93928786-209e-11e8-8aad-f14361d903b4.jpg)

**Comment by aboulch** [comment]
Hello,
Did you generate the views at some point ?

**Comment by zy20091082** [comment]
@aboulch 
Thank you for your reply!
I am confused how to generate the view files. Could you give me some guidance?

**Comment by aboulch** [comment]
You must set in the config.json
"train_create_mesh" : true to generate the meshes
"train_create_views" : true to generate the views (but meshes must have been generated)
"train_create_images" : true to generate the images (but views must have been generated)

It may be a path problem. Please verify in your destination folder what products have been generated.

you can do first, to generate only the meshes:
   "training": true,
    "train_create_mesh" : true,
    "train_create_views" : false,
    "train_create_images" : false,
    "train_rgb" : false,
    "train_composite" : false,
    "train_fusion" : false,
and then to generate only the views:
   "training": true,
    "train_create_mesh" : false,
    "train_create_views" : true,
    "train_create_images" : false,
    "train_rgb" : false,
    "train_composite" : false,
    "train_fusion" : false,

**Comment by zy20091082** [comment]
@aboulch 
Thank you very much! But I met another trouble.
When I train the net and load the pretrained vgg net, I get the following mistake:

**ValueError: Variable conv5_1/weights does not exist, or was created with tf.get_variable(). Did you mean to set reuse=None in VarScope?**

**Comment by aboulch** [comment]
Hello,
I pushed a commit related to weight loading, I removed the use of Kaffe.
It should be easier to use. Tell me if it solves the problem.

**Comment by zy20091082** [comment]
It works!  Thank you again for your work!
