### ISSUE TITLE
Cant' find Sem3D and Semantic3D

### ISSUE THREAD

**Issue by yyuuliang** [aboulch/snapnet#6]
Hi
Thanks for open source this great project! I am trying to run it on my computer, but in step3 and step4, it will fail.  I have built the pointcloud_tools and I can see PcTools.cpython-35m-x86_64-linux-gnu.so in the "lib/python" folder.

Run "python3 sem3d_test_backproj_tf.py --config config.json" will have the following error
Traceback (most recent call last):
  File "sem3d_test_backproj_tf.py", line 85, in <module>
    backproj.createLabelPLY(filename, dir_data=voxels_directory, save_dir=save_dir)
  File "/home/notus/CivilMaps/Deep3D/SnapNET/snapnet/python/tensorflow_tester_backprojeter.py", line 166, in createLabelPLY
    semantizer = Sem3D()
NameError: name 'Sem3D' is not defined

Run "python3 sem3d_test_to_sem3D_labels.py --config config.json" will have this error
Traceback (most recent call last):
  File "sem3d_test_to_sem3D_labels.py", line 7, in <module>
    from python.Semantic3D import Sem3D
ImportError: No module named 'python.Semantic3D

Do you know how to fix this issue?
Thanks.

**Comment by yyuuliang** [comment]
I have put the so file into /usr/lib/python3.5/site-packages. and replace all Sem3D to Semantic3D. I can run the code and get output. Is this correct?
And the outputs are shown below
![screenshot from 2018-03-08 02-27-24](https://user-images.githubusercontent.com/21992330/37146340-4aec5c74-2278-11e8-96ac-4fb560b956b8.png)

**Comment by aboulch** [comment]
Hello,
It looks OK. I will run the code again and make the modifications in the repository as soon as possible.
Thanks for the notification.

**Comment by aboulch** [comment]
It was an error in test mode => I changed it in the repo : "Sem3D()" became "PcTls.Semantic3D()"
