### ISSUE TITLE
Bug in sem3d_test_to_sem3D_labels.py

### ISSUE THREAD

**Issue by syncle** [aboulch/snapnet#8]
This issue related to #6.

In my case ``pointcloud_tools/setup.py`` generates ``PcTools`` on some other location and sem3d_test_to_sem3D_labels.py break. 

The cure is
https://github.com/aboulch/snapnet/blob/4c2447a8e3457e15c34a0187ca55064bb6a5fe74/sem3d_test_to_sem3D_labels.py#L7
should be 
```
from pointcloud_tools.lib.python.PcTools import Semantic3D
```
and 
https://github.com/aboulch/snapnet/blob/4c2447a8e3457e15c34a0187ca55064bb6a5fe74/sem3d_test_to_sem3D_labels.py#L48
should be 
```
semantizer = Semantic3D()
```

**Comment by aboulch** [comment]
Hello,
I made the change semantizer = Sem3D() to semantizer = PcTls.Semantic3D() in the repo.

For the library to be built in the pointcloud_tools, you need to be in the pointcloud_tools directory before calling setup.py:

cd pointcloud_tools
python setup.py install --home="."

I hope that will help.

**Comment by syncle** [comment]
Thanks @aboulch
