### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by syncle** [aboulch/snapnet#9]
I was able to get training result, but the test accuracy is not comparable as stated in the paper.
I used the default configuration, but it just creates a few hundreds of images. As the number of images is small, the training phase finishes in a few minutes. I believe this number of images may not be enough for training. 

I guess this issue should be related to 
https://github.com/aboulch/snapnet/blob/aa0fe5a3e00c5996a4cfaa15b98b9ec8e584aade/config.json#L13
and 
https://github.com/aboulch/snapnet/blob/aa0fe5a3e00c5996a4cfaa15b98b9ec8e584aade/config.json#L18

Can I ask how many number of images were generated to reproduce the number in the paper?

Update: I just checked Computers & Graphics version of the paper, and it says 

> Base on our experiments, we chose to generate 500 views which correspond to an operating point in the curve saturation area.

Is this mean I need to change it to 500? Thanks!

**Comment by aboulch** [comment]
Hello,

Yes I set a low number of images only for pipeline setup. You should use train_cam_number and test_cam_number between 500 and 800. It will be much slower but give much better results.

Anyway it is still future work to improve the camera picking strategy to work with less images.

**Comment by syncle** [comment]
Thanks @aboulch!
